# Generated by Django 5.2.12 on 2026-03-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profession', models.CharField(max_length=100)),
                ('plan', models.CharField(choices=[('free', 'Free Trial'), ('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('plan_activated_at', models.DateTimeField(blank=True, null=True)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('member', 'Member / Family'), ('broker', 'Broker / Consultant'), ('vendor', 'Wedding Vendor'), ('other', 'Other Alliance')], default='member', max_length=50)),
                ('contact', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
