# Generated by Django 5.2.12 on 2026-03-21 15:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.payment_screenshot_path),
        ),
    ]
