# Generated by Django 5.2.12 on 2026-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_member_age_remove_member_family_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='plan_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
