# Generated by Django 5.2.12 on 2026-03-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_member_address_member_brothers_member_family_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='exp_age_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='exp_age_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='exp_caste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='exp_education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='exp_income',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='exp_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
