# Generated by Django 5.2.12 on 2026-03-28 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_member_exp_age_from_member_exp_age_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=70)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_female', to=settings.AUTH_USER_MODEL)),
                ('male', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_male', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
