# Generated by Django 5.2.12 on 2026-03-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='plan',
            name='cta_text',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='plan',
            name='interests_per_day',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='profession_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='plan',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='views_per_day',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='visibility_days',
            field=models.IntegerField(default=30),
        ),
    ]
