# Generated by Django 5.2.12 on 2026-04-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_plan_category_plan_cta_text_plan_interests_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='upgrade_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved')], max_length=10, null=True),
        ),
    ]
