# Generated by Django 5.2.12 on 2026-04-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_member_upgrade_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ['-submitted_on']},
        ),
        migrations.RenameField(
            model_name='successstory',
            old_name='created_at',
            new_name='submitted_on',
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='couple',
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='successstory',
            name='verified',
        ),
        migrations.AddField(
            model_name='successstory',
            name='avatar_idx',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='successstory',
            name='bride_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='successstory',
            name='bride_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='successstory',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='successstory',
            name='community',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='successstory',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='successstory',
            name='groom_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='successstory',
            name='groom_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='successstory',
            name='marriage_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='successstory',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='successstory',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
        migrations.AddField(
            model_name='successstory',
            name='story',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='successstory',
            name='plan',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Basic', 'Basic')], default='Basic', max_length=10),
        ),
    ]
