# Generated by Django 5.2.12 on 2026-04-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_successstory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
