# Generated by Django 5.2.12 on 2026-04-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_member_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
