# Generated by Django 5.2.12 on 2026-04-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_branch_member_added_by_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sapthapadi', max_length=150)),
                ('enable_branches', models.BooleanField(default=True)),
                ('upi_id', models.CharField(blank=True, max_length=150)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.branch')),
            ],
            options={
                'verbose_name': 'App Settings',
            },
        ),
    ]
