# Generated by Django 5.2.12 on 2026-04-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_for',
            field=models.CharField(choices=[('Self', 'Myself'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Friend', 'Friend'), ('Relative', 'Relative')], default='Self', max_length=20),
        ),
    ]
