# Generated by Django 5.2.12 on 2026-04-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_member_profile_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='free_for_female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='free_for_male',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='gender_offer_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
